development:
  adapter: postgresql
  database: david_youtube_development
  pool: 5
  timeout: 5000
  username: david
  password: 12ciaffoniD

test:
  adapter: postgresql
  database: david_youtube_test
  pool: 5
  timeout: 5000
  username: david
  password: 12ciaffoniD

 





